name: Release

# Manual trigger
on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases and tags
      pull-requests: write # Required if you want to create PRs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for correct version calculation

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # xrelease will:
      # 1. Update version in package.json (source of truth)
      # 2. Generate/update CHANGELOG.md
      # 3. Commit these changes with message "chore(release): x.y.z"
      # 4. Create and push git tag vx.y.z
      # 5. Create GitHub release from the changelog
      # 6. Also run any configured pre or post release steps
      - name: Create Release
        run: npx xrelease create --bump ${{ inputs.version_bump }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
